apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app
          image: us-central1-docker.pkg.dev/coral-subject-466408-v9/my-repo/app:latest
          ports:
            - containerPort: 8080